name: Check

on:
  push:

jobs:
  check:
    if: ${{ !startsWith(github.event.head_commit.message, 'release:') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: echo check

      - name: Alpine
        id: alpine
        uses: docker://alpine:latest
        with:
          args: echo alpine

      - name: Foo
        run: echo '${{ toJson(steps.alpine) }}'
