name: Pages

on:
  push:

jobs:
  pages:
    if: ${{ !startsWith(github.event.head_commit.message, 'release:') }}
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Create report
        run: |
          mkdir -p reports
          echo hello > reports/index.html

      - name: Upload report
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
