name: Release Please

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  attestations: write
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4
        id: release

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: echo foo > bar.txt

      - name: Generate artifact attestation
        if: ${{ steps.release.outputs.release_created }}
        id: attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: bar.txt

      - name: Foo
        if: ${{ steps.release.outputs.release_created }}
        run: echo '${{ toJson(steps.attestation) }}'

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./bar.txt
